"""Export fitted KiCad STEP envelopes, or check their placement fingerprint.

Generation needs CadQuery and the geometry JSON from pcb/tools/export_geom.py.
The --check operation uses only the Python standard library.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'pcb'))
import ksexp


def fingerprint(board_path, pcb_z):
    board = ksexp.load(board_path)
    footprints = []
    for fp in ksexp.children(board, 'footprint'):
        props = {p[1]: p[2] for p in ksexp.children(fp, 'property')}
        models = list(ksexp.children(fp, 'model'))
        local_models = []
        for model in models:
            if str(model[1]).startswith('${KIPRJMOD}/'):
                path = board_path.parent / str(model[1]).split('/', 1)[1]
                local_models.append(hashlib.sha256(path.read_bytes()).hexdigest())
        footprints.append([props['Reference'], props['Value'], props.get('MPN', ''), fp[1],
                           ksexp.child(fp, 'at'), ksexp.child(fp, 'layer'),
                           ksexp.child(fp, 'attr'), models, local_models])
    value = [pcb_z, sorted(footprints)]
    return hashlib.sha256(json.dumps(value, sort_keys=True).encode()).hexdigest()


def generate(board_path, step_path, geometry_path, output, pcb_z):
    import cadquery as cq
    original_add = cq.Assembly.add

    def add_unique(self, *args, **kwargs):
        name = kwargs.get('name')
        if name is not None:
            stem, number = name, 1
            while name in self.objects:
                number += 1
                name = f'{stem}_{number}'
            kwargs['name'] = name
        return original_add(self, *args, **kwargs)

    # Repeated STEP product names are legal; CadQuery requires unique names.
    cq.Assembly.add = add_unique
    try:
        assembly = cq.Assembly.load(str(step_path))
    finally:
        cq.Assembly.add = original_add
    board = ksexp.load(board_path)
    fps = {ksexp.ref_of(f): f for f in ksexp.children(board, 'footprint')}
    geom = json.loads(geometry_path.read_text())
    rows = []
    for component in assembly.children:
        if component.obj is not None:
            continue  # Board substrate and copper solids.
        position, _ = component.loc.toTuple()
        fp = min(geom['footprints'], key=lambda f:
                 (f['x'] - position[0]) ** 2 + (f['y'] + position[1]) ** 2)
        if abs(fp['x'] - position[0]) + abs(fp['y'] + position[1]) > 0.01:
            raise ValueError(f'Unmatched STEP component: {component.name}')
        ref = fp['ref']
        if 'dnp' in (ksexp.child(fps[ref], 'attr') or []) or ref in {'SW1', 'SW2'}:
            continue
        bounds = component.toCompound().BoundingBox()
        low = [bounds.xmin, -bounds.ymax, bounds.zmin + pcb_z]
        high = [bounds.xmax, -bounds.ymin, bounds.zmax + pcb_z]
        if ref.startswith('C'):
            # Generic library models omit the selected MLCC height tolerance.
            height = 1.8 if ksexp.prop_value(fps[ref], 'MPN') == 'GRM31CR71H475KA12L' else 1.5
            if fp['layer'] == 'B.Cu':
                low[2] = min(low[2], pcb_z - 0.015 - height)
            else:
                high[2] = max(high[2], pcb_z + 1.2 + 0.015 + height)
        rows.append([ref, [round(v, 5) for v in low],
                     [round(high[i] - low[i], 5) for i in range(3)]])
    expected = {ref for ref, fp in fps.items()
                if list(ksexp.children(fp, 'model'))
                and 'dnp' not in (ksexp.child(fp, 'attr') or [])
                and ref not in {'SW1', 'SW2'}}
    if {row[0] for row in rows} != expected:
        raise ValueError(f'STEP coverage mismatch: {expected ^ {r[0] for r in rows}}')
    output.write_text(
        '// Generated by export_component_bounds.py from the fitted KiCad STEP.\n'
        f'// placement_sha256: {fingerprint(board_path, pcb_z)}\n'
        '// Capacitors reserve 1.5 mm, or 1.8 mm for GRM31CR71H475KA12L; switches have native\n'
        '// enclosure references. Coordinates share the enclosure datum.\n'
        'pcb_component_bounds = [\n' +
        ',\n'.join('    ' + json.dumps(row) for row in sorted(rows)) + '\n];\n')
    print(f'Exported {len(rows)} fitted component envelopes')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('board', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('--step', type=Path)
    parser.add_argument('--geometry', type=Path)
    parser.add_argument('--pcb-z', type=float, default=16.5)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        recorded = re.search(r'placement_sha256: ([0-9a-f]{64})', args.output.read_text())
        if not recorded or recorded[1] != fingerprint(args.board, args.pcb_z):
            raise SystemExit('Regenerate component bounds: PCB placement or local models changed')
        print('PCB component envelope fingerprint matches')
    else:
        if not args.step or not args.geometry:
            parser.error('Generation requires --step and --geometry')
        generate(args.board, args.step, args.geometry, args.output, args.pcb_z)


if __name__ == '__main__':
    main()
