M48
; DRILL file KiCad 10.0.5 date 2026-09-19T23:41:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T23:41:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X72.11Y-55.5
X77.89Y-55.5
T2
X45.46Y-44.5
X50.54Y-43.484
X50.54Y-45.516
T3
X105.0Y-9.5
X105.0Y-18.5
X105.0Y-44.3
X105.0Y-53.3
T4
X37.0Y-58.2
X66.0Y-0.7
X92.0Y-58.2
X97.0Y-0.7
M30
