"""Generate the enclosure's numeric contract; never edits the KiCad sources."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CONTRACT = ROOT / 'hardware/rev_b/contract.json'
OUTPUT = ROOT / 'hardware/rev_b/case/contract.scad'


def outline_points(contract):
    points = contract['pcb']['outline']
    # The reentrant corner is a true R1 arc in KiCad; sample it for OpenSCAD.
    a, b = points[1:3]
    radius = contract['pcb']['inside_radius']
    centre = [a[0], b[1]]
    assert abs(a[1] - b[1] - radius) < 1e-9
    assert abs(b[0] - a[0] - radius) < 1e-9
    arc = [[centre[0] + radius * math.cos(math.radians(t)),
            centre[1] + radius * math.sin(math.radians(t))]
           for t in range(90, -1, -5)]
    return points[:1] + arc + points[3:]


def render(contract):
    lines = ['// Generated by hardware/tools/rev_b/generate_contract.py. Millimetres.']
    for group, values in contract.items():
        if isinstance(values, list):
            lines.append(f'{group} = {json.dumps(values)};')
        if isinstance(values, dict):
            for key, value in values.items():
                if isinstance(value, (int, float, list)) and key != 'pinout':
                    lines.append(f'{group}_{key} = {json.dumps(value)};')
    lines.append('board_polygon = ' + json.dumps(outline_points(contract)) + ';')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    OUTPUT.write_text(render(json.loads(CONTRACT.read_text())))
