CONFIG_CICALA_REV_A=y
CONFIG_CICALA_POWER_DIVIDER_NUM=147
CONFIG_CICALA_POWER_DIVIDER_DEN=47
CONFIG_CICALA_POWER_DIVIDER_SETTLE_MS=200
CONFIG_CICALA_POWER_SAMPLE_MS=1000
CONFIG_CICALA_PANEL_DEEP_SLEEP=y
CONFIG_SSD16XX_PRESERVE_IMAGE_HW_RESET=y
