#!/usr/bin/env python3
"""Generate an Ed25519 bundle or firmware signing keypair.

Bundle keys write a private PEM and the application's raw public-key header.
Firmware keys write the private PEM used by MCUboot sysbuild. The command uses
the system OpenSSL 1.1.1 or newer.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--purpose",
        choices=("bundle", "firmware"),
        default="bundle",
        help="which of the two keys to make (default: bundle)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="private key output path (default: signing_key.pem, gitignored)",
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "firmware"
        / "components"
        / "sync"
        / "trusted_key.h",
    )
    args = parser.parse_args(argv)

    out = args.out or Path("signing_key.pem")

    if out.exists():
        print(f"refusing to overwrite existing {out}", file=sys.stderr)
        return 1

    subprocess.run(["openssl", "genpkey", "-algorithm", "ed25519", "-out", str(out)], check=True)
    out.chmod(0o600)

    if args.purpose == "firmware":
        # MCUboot extracts the public key from this PEM during sysbuild.
        print(f"private key: {out}  (add as GitHub secret FIRMWARE_SIGNING_KEY, then keep offline)")
        print("point SB_CONFIG_BOOT_SIGNATURE_KEY_FILE at it to build a bootloader that trusts it")
        return 0

    der = subprocess.run(
        ["openssl", "pkey", "-in", str(out), "-pubout", "-outform", "DER"],
        capture_output=True,
        check=True,
    ).stdout
    pubkey = der[-32:]

    rows = []
    for i in range(0, 32, 8):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in pubkey[i : i + 8]) + ",")
    body = "\n".join(rows)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(
        "// Ed25519 public key used to verify bundles and firmware manifests.\n"
        "// Generated by tools/keygen.py; keep the private key in BUNDLE_SIGNING_KEY.\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "static const uint8_t CICALA_TRUSTED_KEY[32] = {\n"
        f"{body}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"private key: {out}  (add as GitHub secret BUNDLE_SIGNING_KEY, then keep offline)")
    print(f"public key header: {args.header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
