#!/usr/bin/env python3
"""Generate the ed25519 bundle-signing keypair.

Uses the system openssl (≥ 1.1.1) so tools/ stays free of Python crypto
dependencies. Writes:

  <out>.pem                  private key — NEVER commit; store as the
                             BUNDLE_SIGNING_KEY GitHub Actions secret
  firmware/components/sync/trusted_key.h
                             raw 32-byte public key as a C array (committed)

The raw public key is the last 32 bytes of the SPKI DER — for ed25519 the DER
is a fixed 12-byte prefix plus the key itself.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=Path("signing_key.pem"),
                        help="private key output path (default: signing_key.pem, gitignored)")
    parser.add_argument("--header", type=Path,
                        default=Path(__file__).resolve().parent.parent /
                        "firmware" / "components" / "sync" / "trusted_key.h")
    args = parser.parse_args(argv)

    if args.out.exists():
        print(f"refusing to overwrite existing {args.out}", file=sys.stderr)
        return 1

    subprocess.run(["openssl", "genpkey", "-algorithm", "ed25519",
                    "-out", str(args.out)], check=True)
    args.out.chmod(0o600)
    der = subprocess.run(["openssl", "pkey", "-in", str(args.out),
                          "-pubout", "-outform", "DER"],
                         capture_output=True, check=True).stdout
    pubkey = der[-32:]

    rows = []
    for i in range(0, 32, 8):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in pubkey[i:i + 8]) + ",")
    body = "\n".join(rows)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(
        "// Tischkarte bundle-signing PUBLIC key (ed25519, raw 32 bytes).\n"
        "// Generated by tools/keygen.py — safe to commit. The private key is a\n"
        "// GitHub Actions secret (BUNDLE_SIGNING_KEY); see docs/sync_protocol.md.\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "static const uint8_t TISCHKARTE_TRUSTED_KEY[32] = {\n"
        f"{body}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"private key: {args.out}  (add as GitHub secret BUNDLE_SIGNING_KEY, then keep offline)")
    print(f"public key header: {args.header}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
